<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-03-03T04:06:44Z" name="Suite" finished-at="2021-03-03T04:07:02Z" duration-ms="17443">
    <groups>
    </groups>
    <test started-at="2021-03-03T04:06:44Z" name="Test" finished-at="2021-03-03T04:07:02Z" duration-ms="17443">
      <class name="Test.Empresas">
        <test-method signature="selempresa()[pri:0, instance:Test.Empresas@71e9a896]" started-at="2021-03-02T22:06:51Z" name="selempresa" finished-at="2021-03-02T22:07:02Z" duration-ms="10471" status="FAIL">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:92)
	at org.junit.Assert.assertTrue(Assert.java:43)
	at org.junit.Assert.assertTrue(Assert.java:54)
	at POM.CEmpresa.empresa(CEmpresa.java:19)
	at Test.Empresas.selempresa(Empresas.java:17)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- selempresa -->
      </class> <!-- Test.Empresas -->
      <class name="Test.Global">
        <test-method signature="testeo()[pri:0, instance:Test.Global@6c4f9535]" started-at="2021-03-02T22:06:44Z" name="testeo" finished-at="2021-03-02T22:06:44Z" duration-ms="24" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testeo -->
        <test-method is-config="true" signature="afterSuite()[pri:0, instance:Test.Global@6c4f9535]" started-at="2021-03-02T22:07:02Z" name="afterSuite" finished-at="2021-03-02T22:07:03Z" duration-ms="918" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- Test.Global -->
      <class name="Test.Login">
        <test-method signature="login()[pri:0, instance:Test.Login@285f09de]" started-at="2021-03-02T22:06:44Z" name="login" finished-at="2021-03-02T22:06:51Z" duration-ms="6913" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
      </class> <!-- Test.Login -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
